### ISSUE TITLE
MPDLCD and python3

### ISSUE THREAD

**Issue by mistepien** [rbarrois/mpdlcd#18]
I got something like that on python3.4:
# mpdlcd --help

Traceback (most recent call last):
  File "/usr/bin/mpdlcd", line 10, in <module>
    cli.main(sys.argv)
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/cli.py", line 483, in main
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/cli.py", line 360, in _make_parser
  File "/usr/lib/python3.4/optparse.py", line 999, in add_option
  File "/usr/lib/python3.4/optparse.py", line 580, in __init__
  File "/usr/lib/python3.4/optparse.py", line 669, in _check_choice
optparse.OptionError: option --loglevel: choices must be a list of strings ('dict_keys' supplied)

**Comment by mistepien** [comment]
OK, I managed with it using 2to3, but I get to such "wall":
INFO mpdlcd.mpdwrapper Connecting to MPD server at 127.0.0.1:6600
INFO mpd Calling MPD connect('127.0.0.1', 6600, timeout=None)
INFO mpdlcd.lcdrunner Starting update loop.
DEBUG mpdlcd.mpdwrapper Fetching MPD state
DEBUG mpd Calling MPD status()
DEBUG mpdlcd.mpdwrapper MPD state: 'pause'
DEBUG mpdlcd.mpdhooks Hook state: data changed from {} to {'state': 'pause'}
DEBUG mpdlcd.display_fields Setting widget state-0 to 'PAUSE'
DEBUG mpdlcd.mpdwrapper Fetching MPD song information
DEBUG mpd Calling MPD currentsong()
ERROR mpdlcd.lcdrunner Found exception decoding str is not supported, exiting.
Traceback (most recent call last):
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/lcdrunner.py", line 123, in run
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/utils.py", line 64, in decorated
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/lcdrunner.py", line 111, in update
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdhooks.py", line 77, in handle
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdhooks.py", line 130, in fetch
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/utils.py", line 64, in decorated
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdwrapper.py", line 123, in current_song
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdwrapper.py", line 52, in _decode_dict
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdwrapper.py", line 52, in <genexpr>
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdwrapper.py", line 48, in _decode_text_or_list
  File "root/buildroot-2015.02/output/target/usr/lib/python3.4/site-packages/mpdlcd/mpdwrapper.py", line 40, in _decode_text
TypeError: decoding str is not supported
INFO mpdlcd.lcdrunner Exiting: removing screen MPD

**Comment by rbarrois** [comment]
Yes, the issue here is the same as #16 : ``lcdproc``, the library I use to connect to the LCD, isn't compatible with Python 3 — see also https://github.com/jinglemansweep/lcdproc/issues/7.

I might end up porting lcdproc to Python3...

**Comment by rbarrois** [comment]
Somewhat late, I've finally ported mpdlcd to Python3 (vendoring lcdproc in the process).

Let me know if you meet any issues ;)
